package Web_Basic;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AttendanceDemoOrTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "D:\\Coforge\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void attendanceDemoOr() throws InterruptedException {
    driver.get("https://docs.google.com/forms/d/e/1FAIpQLSc4gcNbOQ4rQWaH1_fudt3io9y5EUjKJ92v5Uxe17tzNIB0fQ/viewform");
    //driver.findElement(By.cssSelector(".quantumWizTextinputPaperinputEl:nth-child(2) .quantumWizTextinputPaperinputInput")).sendKeys("0002-07-29");
    //driver.findElement(By.cssSelector(".quantumWizTextinputPaperinputEl:nth-child(2) .quantumWizTextinputPaperinputInput")).sendKeys("0020-07-29");
    //driver.findElement(By.cssSelector(".quantumWizTextinputPaperinputEl:nth-child(2) .quantumWizTextinputPaperinputInput")).sendKeys("2021-07-29");
    driver.findElement(By.xpath("//div[@class='quantumWizTextinputPaperinputEl freebirdThemedInput freebirdFormviewerComponentsQuestionDateDateInput modeLight']//input[@class='quantumWizTextinputPaperinputInput exportInput']")).sendKeys("29-07-2021");
    driver.findElement(By.cssSelector("[aria-labelledby='i6']")).sendKeys("91449");
    driver.findElement(By.cssSelector("[aria-labelledby='i10']")).sendKeys("Sayan");
    driver.findElement(By.cssSelector("[aria-labelledby='i14']")).sendKeys("Pal");
    driver.findElement(By.cssSelector("[aria-labelledby='i18']")).sendKeys("Sayan.Pal@Coforgetech.com");
    //driver.findElement(By.xpath("//span[@class='appsMaterialWizButtonPaperbuttonLabel quantumWizButtonPaperbuttonLabel exportLabel']")).click();
    Thread.sleep(40000);

  }
}
